package com.example.consumingrest.nytimes_api;

public class StopWord {
    final String stopWords = "'ll\n" +
            "'tis\n" +
            "'twas\n" +
            "'ve\n" +
            "10\n" +
            "39\n" +
            "a\n" +
            "a's\n" +
            "able\n" +
            "ableabout\n" +
            "about\n" +
            "above\n" +
            "abroad\n" +
            "abst\n" +
            "accordance\n" +
            "according\n" +
            "accordingly\n" +
            "across\n" +
            "act\n" +
            "actually\n" +
            "ad\n" +
            "added\n" +
            "adj\n" +
            "adopted\n" +
            "ae\n" +
            "af\n" +
            "affected\n" +
            "affecting\n" +
            "affects\n" +
            "after\n" +
            "afterwards\n" +
            "ag\n" +
            "again\n" +
            "against\n" +
            "ago\n" +
            "ah\n" +
            "ahead\n" +
            "ai\n" +
            "ain't\n" +
            "aint\n" +
            "al\n" +
            "all\n" +
            "allow\n" +
            "allows\n" +
            "almost\n" +
            "alone\n" +
            "along\n" +
            "alongside\n" +
            "already\n" +
            "also\n" +
            "although\n" +
            "always\n" +
            "am\n" +
            "amid\n" +
            "amidst\n" +
            "among\n" +
            "amongst\n" +
            "amoungst\n" +
            "amount\n" +
            "an\n" +
            "and\n" +
            "announce\n" +
            "another\n" +
            "any\n" +
            "anybody\n" +
            "anyhow\n" +
            "anymore\n" +
            "anyone\n" +
            "anything\n" +
            "anyway\n" +
            "anyways\n" +
            "anywhere\n" +
            "ao\n" +
            "apart\n" +
            "apparently\n" +
            "appear\n" +
            "appreciate\n" +
            "appropriate\n" +
            "approximately\n" +
            "aq\n" +
            "ar\n" +
            "are\n" +
            "area\n" +
            "areas\n" +
            "aren\n" +
            "aren't\n" +
            "arent\n" +
            "arise\n" +
            "around\n" +
            "arpa\n" +
            "as\n" +
            "aside\n" +
            "ask\n" +
            "asked\n" +
            "asking\n" +
            "asks\n" +
            "associated\n" +
            "at\n" +
            "au\n" +
            "auth\n" +
            "available\n" +
            "aw\n" +
            "away\n" +
            "awfully\n" +
            "az\n" +
            "b\n" +
            "ba\n" +
            "back\n" +
            "backed\n" +
            "backing\n" +
            "backs\n" +
            "backward\n" +
            "backwards\n" +
            "bb\n" +
            "bd\n" +
            "be\n" +
            "became\n" +
            "because\n" +
            "become\n" +
            "becomes\n" +
            "becoming\n" +
            "been\n" +
            "before\n" +
            "beforehand\n" +
            "began\n" +
            "begin\n" +
            "beginning\n" +
            "beginnings\n" +
            "begins\n" +
            "behind\n" +
            "being\n" +
            "beings\n" +
            "believe\n" +
            "below\n" +
            "beside\n" +
            "besides\n" +
            "best\n" +
            "better\n" +
            "between\n" +
            "beyond\n" +
            "bf\n" +
            "bg\n" +
            "bh\n" +
            "bi\n" +
            "big\n" +
            "bill\n" +
            "billion\n" +
            "biol\n" +
            "bj\n" +
            "bm\n" +
            "bn\n" +
            "bo\n" +
            "both\n" +
            "bottom\n" +
            "br\n" +
            "brief\n" +
            "briefly\n" +
            "bs\n" +
            "bt\n" +
            "but\n" +
            "buy\n" +
            "bv\n" +
            "bw\n" +
            "by\n" +
            "bz\n" +
            "c\n" +
            "c'mon\n" +
            "c's\n" +
            "ca\n" +
            "call\n" +
            "came\n" +
            "can\n" +
            "can't\n" +
            "cannot\n" +
            "cant\n" +
            "caption\n" +
            "case\n" +
            "cases\n" +
            "cause\n" +
            "causes\n" +
            "cc\n" +
            "cd\n" +
            "certain\n" +
            "certainly\n" +
            "cf\n" +
            "cg\n" +
            "ch\n" +
            "changes\n" +
            "ci\n" +
            "ck\n" +
            "cl\n" +
            "clear\n" +
            "clearly\n" +
            "click\n" +
            "cm\n" +
            "cmon\n" +
            "cn\n" +
            "co\n" +
            "co.\n" +
            "com\n" +
            "come\n" +
            "comes\n" +
            "computer\n" +
            "con\n" +
            "concerning\n" +
            "consequently\n" +
            "consider\n" +
            "considering\n" +
            "contain\n" +
            "containing\n" +
            "contains\n" +
            "copy\n" +
            "corresponding\n" +
            "could\n" +
            "could've\n" +
            "couldn\n" +
            "couldn't\n" +
            "couldnt\n" +
            "course\n" +
            "cr\n" +
            "cry\n" +
            "cs\n" +
            "cu\n" +
            "currently\n" +
            "cv\n" +
            "cx\n" +
            "cy\n" +
            "cz\n" +
            "d\n" +
            "dare\n" +
            "daren't\n" +
            "darent\n" +
            "date\n" +
            "de\n" +
            "dear\n" +
            "definitely\n" +
            "describe\n" +
            "described\n" +
            "despite\n" +
            "detail\n" +
            "did\n" +
            "didn\n" +
            "didn't\n" +
            "didnt\n" +
            "differ\n" +
            "different\n" +
            "differently\n" +
            "directly\n" +
            "dj\n" +
            "dk\n" +
            "dm\n" +
            "do\n" +
            "does\n" +
            "doesn\n" +
            "doesn't\n" +
            "doesnt\n" +
            "doing\n" +
            "don\n" +
            "don't\n" +
            "done\n" +
            "dont\n" +
            "doubtful\n" +
            "down\n" +
            "downed\n" +
            "downing\n" +
            "downs\n" +
            "downwards\n" +
            "due\n" +
            "during\n" +
            "dz\n" +
            "e\n" +
            "each\n" +
            "early\n" +
            "ec\n" +
            "ed\n" +
            "edu\n" +
            "ee\n" +
            "effect\n" +
            "eg\n" +
            "eh\n" +
            "eight\n" +
            "eighty\n" +
            "either\n" +
            "eleven\n" +
            "else\n" +
            "elsewhere\n" +
            "empty\n" +
            "end\n" +
            "ended\n" +
            "ending\n" +
            "ends\n" +
            "enough\n" +
            "entirely\n" +
            "er\n" +
            "es\n" +
            "especially\n" +
            "et\n" +
            "et-al\n" +
            "etc\n" +
            "even\n" +
            "evenly\n" +
            "ever\n" +
            "evermore\n" +
            "every\n" +
            "everybody\n" +
            "everyone\n" +
            "everything\n" +
            "everywhere\n" +
            "ex\n" +
            "exactly\n" +
            "example\n" +
            "except\n" +
            "f\n" +
            "face\n" +
            "faces\n" +
            "fact\n" +
            "facts\n" +
            "fairly\n" +
            "far\n" +
            "farther\n" +
            "felt\n" +
            "few\n" +
            "fewer\n" +
            "ff\n" +
            "fi\n" +
            "fifteen\n" +
            "fifth\n" +
            "fifty\n" +
            "fify\n" +
            "fill\n" +
            "find\n" +
            "finds\n" +
            "fire\n" +
            "first\n" +
            "five\n" +
            "fix\n" +
            "fj\n" +
            "fk\n" +
            "fm\n" +
            "fo\n" +
            "followed\n" +
            "following\n" +
            "follows\n" +
            "for\n" +
            "forever\n" +
            "former\n" +
            "formerly\n" +
            "forth\n" +
            "forty\n" +
            "forward\n" +
            "found\n" +
            "four\n" +
            "fr\n" +
            "free\n" +
            "from\n" +
            "front\n" +
            "full\n" +
            "fully\n" +
            "further\n" +
            "furthered\n" +
            "furthering\n" +
            "furthermore\n" +
            "furthers\n" +
            "fx\n" +
            "g\n" +
            "ga\n" +
            "gave\n" +
            "gb\n" +
            "gd\n" +
            "ge\n" +
            "general\n" +
            "generally\n" +
            "get\n" +
            "gets\n" +
            "getting\n" +
            "gf\n" +
            "gg\n" +
            "gh\n" +
            "gi\n" +
            "give\n" +
            "given\n" +
            "gives\n" +
            "giving\n" +
            "gl\n" +
            "gm\n" +
            "gmt\n" +
            "gn\n" +
            "go\n" +
            "goes\n" +
            "going\n" +
            "gone\n" +
            "good\n" +
            "goods\n" +
            "got\n" +
            "gotten\n" +
            "gov\n" +
            "gp\n" +
            "gq\n" +
            "gr\n" +
            "great\n" +
            "greater\n" +
            "greatest\n" +
            "greetings\n" +
            "group\n" +
            "grouped\n" +
            "grouping\n" +
            "groups\n" +
            "gs\n" +
            "gt\n" +
            "gu\n" +
            "gw\n" +
            "gy\n" +
            "h\n" +
            "had\n" +
            "hadn't\n" +
            "hadnt\n" +
            "half\n" +
            "happens\n" +
            "hardly\n" +
            "has\n" +
            "hasn\n" +
            "hasn't\n" +
            "hasnt\n" +
            "have\n" +
            "haven\n" +
            "haven't\n" +
            "havent\n" +
            "having\n" +
            "he\n" +
            "he'd\n" +
            "he'll\n" +
            "he's\n" +
            "hed\n" +
            "hell\n" +
            "hello\n" +
            "help\n" +
            "hence\n" +
            "her\n" +
            "here\n" +
            "here's\n" +
            "hereafter\n" +
            "hereby\n" +
            "herein\n" +
            "heres\n" +
            "hereupon\n" +
            "hers\n" +
            "herself\n" +
            "herse”\n" +
            "hes\n" +
            "hi\n" +
            "hid\n" +
            "high\n" +
            "higher\n" +
            "highest\n" +
            "him\n" +
            "himself\n" +
            "himse”\n" +
            "his\n" +
            "hither\n" +
            "hk\n" +
            "hm\n" +
            "hn\n" +
            "home\n" +
            "homepage\n" +
            "hopefully\n" +
            "how\n" +
            "how'd\n" +
            "how'll\n" +
            "how's\n" +
            "howbeit\n" +
            "however\n" +
            "hr\n" +
            "ht\n" +
            "htm\n" +
            "html\n" +
            "http\n" +
            "hu\n" +
            "hundred\n" +
            "i\n" +
            "i'd\n" +
            "i'll\n" +
            "i'm\n" +
            "i've\n" +
            "i.e.\n" +
            "id\n" +
            "ie\n" +
            "if\n" +
            "ignored\n" +
            "ii\n" +
            "il\n" +
            "ill\n" +
            "im\n" +
            "immediate\n" +
            "immediately\n" +
            "importance\n" +
            "important\n" +
            "in\n" +
            "inasmuch\n" +
            "inc\n" +
            "inc.\n" +
            "indeed\n" +
            "index\n" +
            "indicate\n" +
            "indicated\n" +
            "indicates\n" +
            "information\n" +
            "inner\n" +
            "inside\n" +
            "insofar\n" +
            "instead\n" +
            "int\n" +
            "interest\n" +
            "interested\n" +
            "interesting\n" +
            "interests\n" +
            "into\n" +
            "invention\n" +
            "inward\n" +
            "io\n" +
            "iq\n" +
            "ir\n" +
            "is\n" +
            "isn\n" +
            "isn't\n" +
            "isnt\n" +
            "it\n" +
            "it'd\n" +
            "it'll\n" +
            "it's\n" +
            "itd\n" +
            "itll\n" +
            "its\n" +
            "itself\n" +
            "itse”\n" +
            "ive\n" +
            "j\n" +
            "je\n" +
            "jm\n" +
            "jo\n" +
            "join\n" +
            "jp\n" +
            "just\n" +
            "k\n" +
            "ke\n" +
            "keep\n" +
            "keeps\n" +
            "kept\n" +
            "keys\n" +
            "kg\n" +
            "kh\n" +
            "ki\n" +
            "kind\n" +
            "km\n" +
            "kn\n" +
            "knew\n" +
            "know\n" +
            "known\n" +
            "knows\n" +
            "kp\n" +
            "kr\n" +
            "kw\n" +
            "ky\n" +
            "kz\n" +
            "l\n" +
            "la\n" +
            "large\n" +
            "largely\n" +
            "last\n" +
            "lately\n" +
            "later\n" +
            "latest\n" +
            "latter\n" +
            "latterly\n" +
            "lb\n" +
            "lc\n" +
            "least\n" +
            "length\n" +
            "less\n" +
            "lest\n" +
            "let\n" +
            "let's\n" +
            "lets\n" +
            "li\n" +
            "like\n" +
            "liked\n" +
            "likely\n" +
            "likewise\n" +
            "line\n" +
            "little\n" +
            "lk\n" +
            "ll\n" +
            "long\n" +
            "longer\n" +
            "longest\n" +
            "look\n" +
            "looking\n" +
            "looks\n" +
            "low\n" +
            "lower\n" +
            "lr\n" +
            "ls\n" +
            "lt\n" +
            "ltd\n" +
            "lu\n" +
            "lv\n" +
            "ly\n" +
            "m\n" +
            "ma\n" +
            "made\n" +
            "mainly\n" +
            "make\n" +
            "makes\n" +
            "making\n" +
            "man\n" +
            "many\n" +
            "may\n" +
            "maybe\n" +
            "mayn't\n" +
            "maynt\n" +
            "mc\n" +
            "md\n" +
            "me\n" +
            "mean\n" +
            "means\n" +
            "meantime\n" +
            "meanwhile\n" +
            "member\n" +
            "members\n" +
            "men\n" +
            "merely\n" +
            "mg\n" +
            "mh\n" +
            "microsoft\n" +
            "might\n" +
            "might've\n" +
            "mightn't\n" +
            "mightnt\n" +
            "mil\n" +
            "mill\n" +
            "million\n" +
            "mine\n" +
            "minus\n" +
            "miss\n" +
            "mk\n" +
            "ml\n" +
            "mm\n" +
            "mn\n" +
            "mo\n" +
            "more\n" +
            "moreover\n" +
            "most\n" +
            "mostly\n" +
            "move\n" +
            "mp\n" +
            "mq\n" +
            "mr\n" +
            "mrs\n" +
            "ms\n" +
            "msie\n" +
            "mt\n" +
            "mu\n" +
            "much\n" +
            "mug\n" +
            "must\n" +
            "must've\n" +
            "mustn't\n" +
            "mustnt\n" +
            "mv\n" +
            "mw\n" +
            "mx\n" +
            "my\n" +
            "myself\n" +
            "myse”\n" +
            "mz\n" +
            "n\n" +
            "na\n" +
            "name\n" +
            "namely\n" +
            "nay\n" +
            "nc\n" +
            "nd\n" +
            "ne\n" +
            "near\n" +
            "nearly\n" +
            "necessarily\n" +
            "necessary\n" +
            "need\n" +
            "needed\n" +
            "needing\n" +
            "needn't\n" +
            "neednt\n" +
            "needs\n" +
            "neither\n" +
            "net\n" +
            "netscape\n" +
            "never\n" +
            "neverf\n" +
            "neverless\n" +
            "nevertheless\n" +
            "new\n" +
            "newer\n" +
            "newest\n" +
            "next\n" +
            "nf\n" +
            "ng\n" +
            "ni\n" +
            "nine\n" +
            "ninety\n" +
            "nl\n" +
            "no\n" +
            "no-one\n" +
            "nobody\n" +
            "non\n" +
            "none\n" +
            "nonetheless\n" +
            "noone\n" +
            "nor\n" +
            "normally\n" +
            "nos\n" +
            "not\n" +
            "noted\n" +
            "nothing\n" +
            "notwithstanding\n" +
            "novel\n" +
            "now\n" +
            "nowhere\n" +
            "np\n" +
            "nr\n" +
            "nu\n" +
            "null\n" +
            "number\n" +
            "numbers\n" +
            "nz\n" +
            "o\n" +
            "obtain\n" +
            "obtained\n" +
            "obviously\n" +
            "of\n" +
            "off\n" +
            "often\n" +
            "oh\n" +
            "ok\n" +
            "okay\n" +
            "old\n" +
            "older\n" +
            "oldest\n" +
            "om\n" +
            "omitted\n" +
            "on\n" +
            "once\n" +
            "one\n" +
            "one's\n" +
            "ones\n" +
            "only\n" +
            "onto\n" +
            "open\n" +
            "opened\n" +
            "opening\n" +
            "opens\n" +
            "opposite\n" +
            "or\n" +
            "ord\n" +
            "order\n" +
            "ordered\n" +
            "ordering\n" +
            "orders\n" +
            "org\n" +
            "other\n" +
            "others\n" +
            "otherwise\n" +
            "ought\n" +
            "oughtn't\n" +
            "oughtnt\n" +
            "our\n" +
            "ours\n" +
            "ourselves\n" +
            "out\n" +
            "outside\n" +
            "over\n" +
            "overall\n" +
            "owing\n" +
            "own\n" +
            "p\n" +
            "pa\n" +
            "page\n" +
            "pages\n" +
            "part\n" +
            "parted\n" +
            "particular\n" +
            "particularly\n" +
            "parting\n" +
            "parts\n" +
            "past\n" +
            "pe\n" +
            "per\n" +
            "perhaps\n" +
            "pf\n" +
            "pg\n" +
            "ph\n" +
            "pk\n" +
            "pl\n" +
            "place\n" +
            "placed\n" +
            "places\n" +
            "please\n" +
            "plus\n" +
            "pm\n" +
            "pmid\n" +
            "pn\n" +
            "point\n" +
            "pointed\n" +
            "pointing\n" +
            "points\n" +
            "poorly\n" +
            "possible\n" +
            "possibly\n" +
            "potentially\n" +
            "pp\n" +
            "pr\n" +
            "predominantly\n" +
            "present\n" +
            "presented\n" +
            "presenting\n" +
            "presents\n" +
            "presumably\n" +
            "previously\n" +
            "primarily\n" +
            "probably\n" +
            "problem\n" +
            "problems\n" +
            "promptly\n" +
            "proud\n" +
            "provided\n" +
            "provides\n" +
            "pt\n" +
            "put\n" +
            "puts\n" +
            "pw\n" +
            "py\n" +
            "q\n" +
            "qa\n" +
            "que\n" +
            "quickly\n" +
            "quite\n" +
            "qv\n" +
            "r\n" +
            "ran\n" +
            "rather\n" +
            "rd\n" +
            "re\n" +
            "readily\n" +
            "really\n" +
            "reasonably\n" +
            "recent\n" +
            "recently\n" +
            "ref\n" +
            "refs\n" +
            "regarding\n" +
            "regardless\n" +
            "regards\n" +
            "related\n" +
            "relatively\n" +
            "research\n" +
            "reserved\n" +
            "respectively\n" +
            "resulted\n" +
            "resulting\n" +
            "results\n" +
            "right\n" +
            "ring\n" +
            "ro\n" +
            "room\n" +
            "rooms\n" +
            "round\n" +
            "ru\n" +
            "run\n" +
            "rw\n" +
            "s\n" +
            "sa\n" +
            "said\n" +
            "same\n" +
            "saw\n" +
            "say\n" +
            "saying\n" +
            "says\n" +
            "sb\n" +
            "sc\n" +
            "sd\n" +
            "se\n" +
            "sec\n" +
            "second\n" +
            "secondly\n" +
            "seconds\n" +
            "section\n" +
            "see\n" +
            "seeing\n" +
            "seem\n" +
            "seemed\n" +
            "seeming\n" +
            "seems\n" +
            "seen\n" +
            "sees\n" +
            "self\n" +
            "selves\n" +
            "sensible\n" +
            "sent\n" +
            "serious\n" +
            "seriously\n" +
            "seven\n" +
            "seventy\n" +
            "several\n" +
            "sg\n" +
            "sh\n" +
            "shall\n" +
            "shan't\n" +
            "shant\n" +
            "she\n" +
            "she'd\n" +
            "she'll\n" +
            "she's\n" +
            "shed\n" +
            "shell\n" +
            "shes\n" +
            "should\n" +
            "should've\n" +
            "shouldn\n" +
            "shouldn't\n" +
            "shouldnt\n" +
            "show\n" +
            "showed\n" +
            "showing\n" +
            "shown\n" +
            "showns\n" +
            "shows\n" +
            "si\n" +
            "side\n" +
            "sides\n" +
            "significant\n" +
            "significantly\n" +
            "similar\n" +
            "similarly\n" +
            "since\n" +
            "sincere\n" +
            "site\n" +
            "six\n" +
            "sixty\n" +
            "sj\n" +
            "sk\n" +
            "sl\n" +
            "slightly\n" +
            "sm\n" +
            "small\n" +
            "smaller\n" +
            "smallest\n" +
            "sn\n" +
            "so\n" +
            "some\n" +
            "somebody\n" +
            "someday\n" +
            "somehow\n" +
            "someone\n" +
            "somethan\n" +
            "something\n" +
            "sometime\n" +
            "sometimes\n" +
            "somewhat\n" +
            "somewhere\n" +
            "soon\n" +
            "sorry\n" +
            "specifically\n" +
            "specified\n" +
            "specify\n" +
            "specifying\n" +
            "sr\n" +
            "st\n" +
            "state\n" +
            "states\n" +
            "still\n" +
            "stop\n" +
            "strongly\n" +
            "su\n" +
            "sub\n" +
            "substantially\n" +
            "successfully\n" +
            "such\n" +
            "sufficiently\n" +
            "suggest\n" +
            "sup\n" +
            "sure\n" +
            "sv\n" +
            "sy\n" +
            "system\n" +
            "sz\n" +
            "t\n" +
            "t's\n" +
            "take\n" +
            "taken\n" +
            "taking\n" +
            "tc\n" +
            "td\n" +
            "tell\n" +
            "ten\n" +
            "tends\n" +
            "test\n" +
            "text\n" +
            "tf\n" +
            "tg\n" +
            "th\n" +
            "than\n" +
            "thank\n" +
            "thanks\n" +
            "thanx\n" +
            "that\n" +
            "that'll\n" +
            "that's\n" +
            "that've\n" +
            "thatll\n" +
            "thats\n" +
            "thatve\n" +
            "the\n" +
            "their\n" +
            "theirs\n" +
            "them\n" +
            "themselves\n" +
            "then\n" +
            "thence\n" +
            "there\n" +
            "there'd\n" +
            "there'll\n" +
            "there're\n" +
            "there's\n" +
            "there've\n" +
            "thereafter\n" +
            "thereby\n" +
            "thered\n" +
            "therefore\n" +
            "therein\n" +
            "therell\n" +
            "thereof\n" +
            "therere\n" +
            "theres\n" +
            "thereto\n" +
            "thereupon\n" +
            "thereve\n" +
            "these\n" +
            "they\n" +
            "they'd\n" +
            "they'll\n" +
            "they're\n" +
            "they've\n" +
            "theyd\n" +
            "theyll\n" +
            "theyre\n" +
            "theyve\n" +
            "thick\n" +
            "thin\n" +
            "thing\n" +
            "things\n" +
            "think\n" +
            "thinks\n" +
            "third\n" +
            "thirty\n" +
            "this\n" +
            "thorough\n" +
            "thoroughly\n" +
            "those\n" +
            "thou\n" +
            "though\n" +
            "thoughh\n" +
            "thought\n" +
            "thoughts\n" +
            "thousand\n" +
            "three\n" +
            "throug\n" +
            "through\n" +
            "throughout\n" +
            "thru\n" +
            "thus\n" +
            "til\n" +
            "till\n" +
            "tip\n" +
            "tis\n" +
            "tj\n" +
            "tk\n" +
            "tm\n" +
            "tn\n" +
            "to\n" +
            "today\n" +
            "together\n" +
            "too\n" +
            "took\n" +
            "top\n" +
            "toward\n" +
            "towards\n" +
            "tp\n" +
            "tr\n" +
            "tried\n" +
            "tries\n" +
            "trillion\n" +
            "truly\n" +
            "try\n" +
            "trying\n" +
            "ts\n" +
            "tt\n" +
            "turn\n" +
            "turned\n" +
            "turning\n" +
            "turns\n" +
            "tv\n" +
            "tw\n" +
            "twas\n" +
            "twelve\n" +
            "twenty\n" +
            "twice\n" +
            "two\n" +
            "tz\n" +
            "u\n" +
            "ua\n" +
            "ug\n" +
            "uk\n" +
            "um\n" +
            "un\n" +
            "under\n" +
            "underneath\n" +
            "undoing\n" +
            "unfortunately\n" +
            "unless\n" +
            "unlike\n" +
            "unlikely\n" +
            "until\n" +
            "unto\n" +
            "up\n" +
            "upon\n" +
            "ups\n" +
            "upwards\n" +
            "us\n" +
            "use\n" +
            "used\n" +
            "useful\n" +
            "usefully\n" +
            "usefulness\n" +
            "uses\n" +
            "using\n" +
            "usually\n" +
            "uucp\n" +
            "uy\n" +
            "uz\n" +
            "v\n" +
            "va\n" +
            "value\n" +
            "various\n" +
            "vc\n" +
            "ve\n" +
            "versus\n" +
            "very\n" +
            "vg\n" +
            "vi\n" +
            "via\n" +
            "viz\n" +
            "vn\n" +
            "vol\n" +
            "vols\n" +
            "vs\n" +
            "vu\n" +
            "w\n" +
            "want\n" +
            "wanted\n" +
            "wanting\n" +
            "wants\n" +
            "was\n" +
            "wasn\n" +
            "wasn't\n" +
            "wasnt\n" +
            "way\n" +
            "ways\n" +
            "we\n" +
            "we'd\n" +
            "we'll\n" +
            "we're\n" +
            "we've\n" +
            "web\n" +
            "webpage\n" +
            "website\n" +
            "wed\n" +
            "welcome\n" +
            "well\n" +
            "wells\n" +
            "went\n" +
            "were\n" +
            "weren\n" +
            "weren't\n" +
            "werent\n" +
            "weve\n" +
            "wf\n" +
            "what\n" +
            "what'd\n" +
            "what'll\n" +
            "what's\n" +
            "what've\n" +
            "whatever\n" +
            "whatll\n" +
            "whats\n" +
            "whatve\n" +
            "when\n" +
            "when'd\n" +
            "when'll\n" +
            "when's\n" +
            "whence\n" +
            "whenever\n" +
            "where\n" +
            "where'd\n" +
            "where'll\n" +
            "where's\n" +
            "whereafter\n" +
            "whereas\n" +
            "whereby\n" +
            "wherein\n" +
            "wheres\n" +
            "whereupon\n" +
            "wherever\n" +
            "whether\n" +
            "which\n" +
            "whichever\n" +
            "while\n" +
            "whilst\n" +
            "whim\n" +
            "whither\n" +
            "who\n" +
            "who'd\n" +
            "who'll\n" +
            "who's\n" +
            "whod\n" +
            "whoever\n" +
            "whole\n" +
            "wholl\n" +
            "whom\n" +
            "whomever\n" +
            "whos\n" +
            "whose\n" +
            "why\n" +
            "why'd\n" +
            "why'll\n" +
            "why's\n" +
            "widely\n" +
            "width\n" +
            "will\n" +
            "willing\n" +
            "wish\n" +
            "with\n" +
            "within\n" +
            "without\n" +
            "won\n" +
            "won't\n" +
            "wonder\n" +
            "wont\n" +
            "words\n" +
            "work\n" +
            "worked\n" +
            "working\n" +
            "works\n" +
            "world\n" +
            "would\n" +
            "would've\n" +
            "wouldn\n" +
            "wouldn't\n" +
            "wouldnt\n" +
            "ws\n" +
            "www\n" +
            "x\n" +
            "y\n" +
            "ye\n" +
            "year\n" +
            "years\n" +
            "yes\n" +
            "yet\n" +
            "you\n" +
            "you'd\n" +
            "you'll\n" +
            "you're\n" +
            "you've\n" +
            "youd\n" +
            "youll\n" +
            "young\n" +
            "younger\n" +
            "youngest\n" +
            "your\n" +
            "youre\n" +
            "yours\n" +
            "yourself\n" +
            "yourselves\n" +
            "youve\n" +
            "yt\n" +
            "yu\n" +
            "z\n" +
            "za\n" +
            "zero\n" +
            "zm\n" +
            "zr";

}
